services:
  bitcoin-sentiment-bot:
    build: .
    container_name: bitcoin_sentiment_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - TORCH_HOME=/app/data/torch
    networks:
      - bot-network
    mem_limit: 1.5g
    cpus: 1.5
    ports:
      - "8000:8000"  # Expose web dashboard

networks:
  bot-network:
    driver: bridge
